package org.zoxweb.server.fsm;

import java.util.function.Supplier;

/**
 * TriggerInt represents an event that drives processing in the state machine.
 * <p>
 * Triggers are the primary mechanism for communication within the state machine. They can be
 * generated by external sources (e.g., network events, user input) or internally by
 * {@link TriggerConsumerInt} implementations to continue the processing flow.
 * </p>
 *
 * <h2>Design Philosophy</h2>
 * <ul>
 *   <li>Triggers can arrive at any time from any thread - no ordering guarantees</li>
 *   <li>Each trigger carries optional data of type {@code D}</li>
 *   <li>The canonical ID determines which TriggerConsumer(s) will process the trigger</li>
 *   <li>Triggers are immutable once created - thread-safe by design</li>
 * </ul>
 *
 * <h2>Trigger Identification</h2>
 * <ul>
 *   <li><b>Canonical ID</b> - String identifier that maps to TriggerConsumer(s)</li>
 *   <li><b>Unique ID</b> - Monotonically increasing long for tracking/debugging across all state machines</li>
 *   <li><b>Timestamp</b> - Creation time in milliseconds for metrics and debugging</li>
 * </ul>
 *
 * <h2>Data Access</h2>
 * Implements {@link Supplier} to provide trigger data via {@link #get()}. The data type is
 * generic, allowing triggers to carry any payload needed by the consumer.
 *
 * <h2>Usage Pattern</h2>
 * <pre>{@code
 * // Create and publish a trigger
 * Trigger<MyData> trigger = new Trigger<>(this, "PROCESS_DATA", currentState, myData);
 * stateMachine.publish(trigger);
 *
 * // Or use convenience methods from TriggerConsumer
 * publish("NEXT_STEP", resultData);
 * }</pre>
 *
 * @param <D> the type of data carried by this trigger (can be {@code Void} for data-less triggers)
 * @see TriggerConsumerInt
 * @see StateMachineInt#publish(TriggerInt)
 */
public interface TriggerInt<D>
        extends Supplier<D> {
    /**
     * @return Points to the issuing state
     */
    StateInt lastState();

    /**
     * @return the unique identifier of the TriggerConsumer that will process the trigger event
     */
    String getCanonicalID();

    /**
     * @return number unique id of any generated triggers of all StateMachines across all state and consumers
     */
    long getID();

    /**
     * @return in millis when the trigger was generated
     */
    long getTimestamp();
}
